model:
  name: netmamba
  d_model: 256
  n_layers: 6
  dropout: 0.1
  max_len: 256
  feature_dim: 256

head:
  num_classes: infer
  dropout: 0.1

tokenizer:
  preset: debunk_v1

train:
  epochs: 10
  batch_size: 64
  lr: 3.0e-4
  weight_decay: 0.01
  optimizer: adamw
  amp: true
  grad_clip: 1.0
  scheduler:
    name: cosine
    warmup_steps: 500
    max_steps: 10000
  early_stopping:
    enabled: false
    patience: 5

log:
  log_interval: 50
  eval_interval: 200
  save_interval: 500

system:
  num_workers: 4
  pin_memory: true
  deterministic: true


